# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
language: "en"
enableGlobDot: true
ignorePaths:
  - .git/
  - ./data/
  - pnpm-lock.yaml
  - contributions.md
ignoreWords:
  - Tonygeo
  - Hellooo
  - apfelstrudel
  - hyperupcall
  - xournalpp
  - commitizen
  - davidNicolas-cecs
